
iterator = range(3).__iter__()
try:
    print(iterator.__next__()
    print(iterator.__next__()
    print(iterator.__next__()
    print(iterator.__next__()
except Exception as e:
    print(e)
    print('예외가 발생했습니다.'e)

출력
'''
0
1
2

예외가 발생했습니다.
'''